
services:
  mongo:
    image: mongo:6
    container_name: parse-serve-mongo
    restart: unless-stopped
    ports:
      - "${PARSE_SERVER_MONGO}:27017"
    volumes:
      - mongo_data:/data/db

  parse-server:
    image: parseplatform/parse-server
    container_name: parse-server
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "${PARSE_SERVER_PORT}:1337"
    environment:
      PARSE_SERVER_APPLICATION_ID: ${PARSE_SERVER_APPLICATION_ID}
      PARSE_SERVER_MASTER_KEY: ${PARSE_SERVER_MASTER_KEY}
      PARSE_SERVER_DATABASE_URI: ${PARSE_SERVER_DATABASE_URI}
      PARSE_SERVER_URL: ${PARSE_SERVER_URL}
      PARSE_SERVER_ALLOW_ORIGIN: ${PARSE_SERVER_ALLOW_ORIGIN}
      PARSE_SERVER_ENABLE_SCHEMA_PATCH: true
      PARSE_SERVER_MASTER_KEY_IPS: "0.0.0.0/0"
      
volumes:
  mongo_data: